setup <- function(){
  p_needed <- c("dplyr", "stringr", "lubridate", "readxl", "rstudioapi", "haven", "magrittr")
  packages <- rownames(installed.packages())
  p_to_install <- p_needed[!(p_needed %in% packages)]
  if (length(p_to_install) > 0) {
    install.packages(p_to_install)
  }
  lapply(p_needed, require, character.only = TRUE)
  setwd(dirname(getActiveDocumentContext()$path)) # set directory to the document 
}
setup()

data <- readRDS("../data/WVS_TimeSeries_1981_2020.RDS") 
############# Merging WVS and NELDA #######
# data <- readRDS("WVS_TimeSeries_1981_2020.RDS") 
NELDA <- readRDS("../data/NELDA.RDS")
# EVS <- read_dta("ZA4804_v3-1-0.dta") saveRDS(EVS, "EVS_TimeSeries_1981_2008")
# data %<>% bind_rows(., EVS)
# 
# NELDA$date <- as_date(paste0(NELDA$year, "-", str_pad(str_remove(NELDA$mmdd,
# '.{2}$'), width=2, side="left", pad="0"), "-", str_extract(NELDA$mmdd,
# '.{2}$')))
# 
# 
# data$date <- ymd(as.numeric(data$S012))
# 
# WVS_countries <- data %>% select(COW_ALPHA, COW_NUM, COUNTRY_ALPHA, date) %>%
# distinct() 
# WVS_NELDA <- tibble()
# 
# for (i in 1:nrow(WVS_countries)){ 
#   try({NELDA %>% filter(ccode == WVS_countries$COW_NUM[i], date <= WVS_countries$date[i]) %>% 
#       filter(date == max(date)) %>% 
#       mutate(days_after_elections_all = WVS_countries$date[i] - date) %>% 
#       bind_cols(., WVS_countries[i,])  -> temp
#     WVS_NELDA %<>% bind_rows(temp, .)}) }
# 
# 
# data %>% left_join(., WVS_NELDA) -> WVS_NELDA
# 
# WVS_NELDA <- readRDS("WVS_NELDA.RDS")
# # saveRDS(WVS_NELDA, 'WVS_NELDA.RDS')



############# WVS Analysis #######
# Variables we may need
# A165	Most people can be trusted	Generally speaking, would you say that most people can be trusted or that you need to be very careful in dealing with people?	1  Most people can be trusted_x000D_ 2  Need to be very careful_x000D_ -1  Don??t know_x000D_ -2  No answer_x000D_ -4  Not asked_x000D_ 
# S020	Year survey
# COW_NUM	CoW country code numeric
# A062	How often discusses political matters with friends	When you get together with your friends, would you say you discuss political matters frequently, occasionally or never?	1  Frequently_x000D_ 2  Occasionally_x000D_ 3  Never_x000D_ -1  Don??t know_x000D_ -2  No answer_x000D_ -4  Not asked_x000D_ -5  Missing; Unknown_x000D_ 
# E023	Interest in politics	How interested would you say you are in politics?	1  Very interested_x000D_ 2  Somewhat interested_x000D_ 3  Not very interested_x000D_ 4  Not at all interested_x000D_ -1  Don??t know_x000D_ -2  No answer_x000D_ -4  Not asked_x000D_ -5  Missing; Unknown_x000D_ 
# E069_02	Confidence: Armed Forces	I am going to name a number of organizations. For each one, could you tell me how much confidence you have in them: is it a great deal of confidence, quite a lot of confidence, not very much confidence or none at all?  The armed forces	1  A great deal_x000D_ 2  Quite a lot_x000D_ 3  Not very much_x000D_ 4  None at all_x000D_ -1  Don??t know_x000D_ -2  No answer_x000D_ -4  Not asked_x000D_ -5  Missing; Unknown_x000D_ 
# E069_03	Confidence: Education System	Please look at this card and tell me, for each item listed, how much confidence you have in them, is it a great deal, quite a lot, not very much or none at all?  How much confidence in: education system	1  A great deal_x000D_ 2  Quite a lot_x000D_ 3  Not very much_x000D_ 4  None at all_x000D_ -1  Don??t know_x000D_ -2  No answer_x000D_ -4  Not asked_x000D_ -5  Missing; Unknown_x000D_ 
# E069_04	Confidence: The Press	I am going to name a number of organizations. For each one, could you tell me how much confidence you have in them: is it a great deal of confidence, quite a lot of confidence, not very much confidence or none at all?  The press	1  A great deal_x000D_ 2  Quite a lot_x000D_ 3  Not very much_x000D_ 4  None at all_x000D_ -1  Don??t know_x000D_ -2  No answer_x000D_ -4  Not asked_x000D_ -5  Missing; Unknown_x000D_ 
# E069_05	Confidence: Labour Unions	I am going to name a number of organizations. For each one, could you tell me how much confidence you have in them: is it a great deal of confidence, quite a lot of confidence, not very much confidence or none at all?  Labour Unions	1  A great deal_x000D_ 2  Quite a lot_x000D_ 3  Not very much_x000D_ 4  None at all_x000D_ -1  Don??t know_x000D_ -2  No answer_x000D_ -4  Not asked_x000D_ -5  Missing; Unknown_x000D_ 
# E069_06	Confidence: The Police	I am going to name a number of organizations. For each one, could you tell me how much confidence you have in them: is it a great deal of confidence, quite a lot of confidence, not very much confidence or none at all?  The police	1  A great deal_x000D_ 2  Quite a lot_x000D_ 3  Not very much_x000D_ 4  None at all_x000D_ -1  Don??t know_x000D_ -2  No answer_x000D_ -4  Not asked_x000D_ -5  Missing; Unknown_x000D_ 
# E069_07	Confidence: Parliament	I am going to name a number of organizations. For each one, could you tell me how much confidence you have in them: is it a great deal of confidence, quite a lot of confidence, not very much confidence or none at all?  Parliament	1  A great deal_x000D_ 2  Quite a lot_x000D_ 3  Not very much_x000D_ 4  None at all_x000D_ -1  Don??t know_x000D_ -2  No answer_x000D_ -4  Not asked_x000D_ -5  Missing; Unknown_x000D_ 
# E069_08	Confidence: The Civil Services	I am going to name a number of organizations. For each one, could you tell me how much confidence you have in them: is it a great deal of confidence, quite a lot of confidence, not very much confidence or none at all?  The Civil Services	1  A great deal_x000D_ 2  Quite a lot_x000D_ 3  Not very much_x000D_ 4  None at all_x000D_ -1  Don??t know_x000D_ -2  No answer_x000D_ -4  Not asked_x000D_ -5  Missing; Unknown_x000D_ 
# E069_09	Confidence: Social Security System	Please look at this card and tell me, for each item listed, how much confidence you have in them, is it a great deal, quite a lot, not very much or none at all?  How much confidence in: social security system	1  A great deal_x000D_ 2  Quite a lot_x000D_ 3  Not very much_x000D_ 4  None at all_x000D_ -1  Don??t know_x000D_ -2  No answer_x000D_ -4  Not asked_x000D_ -5  Missing; Unknown_x000D_ 
# E069_10	Confidence: Television	I am going to name a number of organizations. For each one, could you tell me how much confidence you have in them: is it a great deal of confidence, quite a lot of confidence, not very much confidence or none at all?  Television	1  A great deal_x000D_ 2  Quite a lot_x000D_ 3  Not very much_x000D_ 4  None at all_x000D_ -1  Don??t know_x000D_ -2  No answer_x000D_ -4  Not asked_x000D_ -5  Missing; Unknown_x000D_ 
# E069_11	Confidence: The Government	I am going to name a number of organizations. For each one, could you tell me how much confidence you have in them: is it a great deal of confidence, quite a lot of confidence, not very much confidence or none at all?  The government (in your nation's capital)	1  A great deal_x000D_ 2  Quite a lot_x000D_ 3  Not very much_x000D_ 4  None at all_x000D_ -1  Don??t know_x000D_ -2  No answer_x000D_ -4  Not asked_x000D_ -5  Missing; Unknown_x000D_ 
# E069_12	Confidence: The Political Parties	I am going to name a number of organizations. For each one, could you tell me how much confidence you have in them: is it a great deal of confidence, quite a lot of confidence, not very much confidence or none at all?  Political Parties	1  A great deal_x000D_ 2  Quite a lot_x000D_ 3  Not very much_x000D_ 4  None at all_x000D_ -1  Don??t know_x000D_ -2  No answer_x000D_ -4  Not asked_x000D_ -5  Missing; Unknown_x000D_ 
# E069_13	Confidence: Major Companies	I am going to name a number of organizations. For each one, could you tell me how much confidence you have in them: is it a great deal of confidence, quite a lot of confidence, not very much confidence or none at all?  Major Companies	1  A great deal_x000D_ 2  Quite a lot_x000D_ 3  Not very much_x000D_ 4  None at all_x000D_ -1  Don??t know_x000D_ -2  No answer_x000D_ -4  Not asked_x000D_ -5  Missing; Unknown_x000D_ 
# E069_14	Confidence: The Environmental Protection Movement	I am going to name a number of organizations. For each one, could you tell me how much confidence you have in them: is it a great deal of confidence, quite a lot of confidence, not very much confidence or none at all?  Environmental organizations	1  A great deal_x000D_ 2  Quite a lot_x000D_ 3  Not very much_x000D_ 4  None at all_x000D_ -1  Don??t know_x000D_ -2  No answer_x000D_ -4  Not asked_x000D_ -5  Missing; Unknown_x000D_ 
# E069_15	Confidence: The Women??s Movement	I am going to name a number of organizations. For each one, could you tell me how much confidence you have in them: is it a great deal of confidence, quite a lot of confidence, not very much confidence or none at all?  Women??s organizations	1  A great deal_x000D_ 2  Quite a lot_x000D_ 3  Not very much_x000D_ 4  None at all_x000D_ -1  Don??t know_x000D_ -2  No answer_x000D_ -4  Not asked_x000D_ -5  Missing; Unknown_x000D_ 
# E069_16	Confidence: Health Care System	Please look at this card and tell me, for each item listed, how much confidence you have in them, is it a great deal, quite a lot, not very much or none at all?  How much confidence in: health care system	1  A great deal_x000D_ 2  Quite a lot_x000D_ 3  Not very much_x000D_ 4  None at all_x000D_ -1  Don??t know_x000D_ -2  No answer_x000D_ -4  Not asked_x000D_ -5  Missing; Unknown_x000D_ 
# E069_17	Confidence: Justice System/Courts	I am going to name a number of organizations. For each one, could you tell me how much confidence you have in them: is it a great deal of confidence, quite a lot of confidence, not very much confidence or none at all?  The courts	1  A great deal_x000D_ 2  Quite a lot_x000D_ 3  Not very much_x000D_ 4  None at all_x000D_ -1  Don??t know_x000D_ -2  No answer_x000D_ -4  Not asked_x000D_ -5  Missing; Unknown_x000D_ 
# E069_18	Confidence: The European Union	I am going to name a number of organizations. For each one, could you tell me how much confidence you have in them: is it a great deal of confidence, quite a lot of confidence, not very much confidence or none at all?  The European Union	1  A great deal_x000D_ 2  Quite a lot_x000D_ 3  Not very much_x000D_ 4  None at all_x000D_ -1  Don??t know_x000D_ -2  No answer_x000D_ -4  Not asked_x000D_ -5  Missing; Unknown_x000D_ 
# E069_19	Confidence: NATO	I am going to name a number of organizations. For each one, could you tell me how much confidence you have in them: is it a great deal of confidence, quite a lot of confidence, not very much confidence or none at all?  The North Atlantic Treaty Organization (NATO)	1  A great deal_x000D_ 2  Quite a lot_x000D_ 3  Not very much_x000D_ 4  None at all_x000D_ -1  Don??t know_x000D_ -2  No answer_x000D_ -4  Not asked_x000D_ -5  Missing; Unknown_x000D_ 
# E069_20	Confidence: The United Nations	I am going to name a number of organizations. For each one, could you tell me how much confidence you have in them: is it a great deal of confidence, quite a lot of confidence, not very much confidence or none at all?  The United Nations	1  A great deal_x000D_ 2  Quite a lot_x000D_ 3  Not very much_x000D_ 4  None at all_x000D_ -1  Don??t know_x000D_ -2  No answer_x000D_ -4  Not asked_x000D_ -5  Missing; Unknown_x000D_ 
# E069_21	Confidence: The Arab League	I am going to name a number of organizations. For each one, could you tell me how much confidence you have in them: is it a great deal of confidence, quite a lot of confidence, not very much confidence or none at all?  The Arab League	1  A great deal_x000D_ 2  Quite a lot_x000D_ 3  Not very much_x000D_ 4  None at all_x000D_ -1  Don??t know_x000D_ -2  No answer_x000D_ -4  Not asked_x000D_ -5  Missing; Unknown_x000D_ 
# E069_22	Confidence: The Association of South East Asian Nations -ASEAN	I am going to name a number of organizations. For each one, could you tell me how much confidence you have in them: is it a great deal of confidence, quite a lot of confidence, not very much confidence or none at all?  The Association of South East Asian Nations -ASEAN	1  A great deal_x000D_ 2  Quite a lot_x000D_ 3  Not very much_x000D_ 4  None at all_x000D_ -1  Don??t know_x000D_ -2  No answer_x000D_ -4  Not asked_x000D_ -5  Missing; Unknown_x000D_ 
# E069_23	Confidence: The Organization for African Unity-OAU	I am going to name a number of organizations. For each one, could you tell me how much confidence you have in them: is it a great deal of confidence, quite a lot of confidence, not very much confidence or none at all?	1  A great deal_x000D_ 2  Quite a lot_x000D_ 3  Not very much_x000D_ 4  None at all_x000D_ -1  Don??t know_x000D_ -2  No answer_x000D_ -4  Not asked_x000D_ -5  Missing; Unknown_x000D_ 
# E069_24	Confidence: The NAFTA	I am going to name a number of organizations. For each one, could you tell me how much confidence you have in them: is it a great deal of confidence, quite a lot of confidence, not very much confidence or none at all?  The NAFTA	1  A great deal_x000D_ 2  Quite a lot_x000D_ 3  Not very much_x000D_ 4  None at all_x000D_ -1  Don??t know_x000D_ -2  No answer_x000D_ -4  Not asked_x000D_ -5  Missing; Unknown_x000D_ 
# E069_25	Confidence: The Andean pact	I am going to name a number of organizations. For each one, could you tell me how much confidence you have in them: is it a great deal of confidence, quite a lot of confidence, not very much confidence or none at all?	1  A great deal_x000D_ 2  Quite a lot_x000D_ 3  Not very much_x000D_ 4  None at all_x000D_ -1  Don??t know_x000D_ -2  No answer_x000D_ -4  Not asked_x000D_ -5  Missing; Unknown_x000D_ 
# E069_26	Confidence: The Mercosur	I am going to name a number of organizations. For each one, could you tell me how much confidence you have in them: is it a great deal of confidence, quite a lot of confidence, not very much confidence or none at all?  The Mercosur	1  A great deal_x000D_ 2  Quite a lot_x000D_ 3  Not very much_x000D_ 4  None at all_x000D_ -1  Don??t know_x000D_ -2  No answer_x000D_ -4  Not asked_x000D_ -5  Missing; Unknown_x000D_ 
# E069_27	Confidence: The SAARC	I am going to name a number of organizations. For each one, could you tell me how much confidence you have in them: is it a great deal of confidence, quite a lot of confidence, not very much confidence or none at all?  The SAARC	1  A great deal_x000D_ 2  Quite a lot_x000D_ 3  Not very much_x000D_ 4  None at all_x000D_ -1  Don??t know_x000D_ -2  No answer_x000D_ -4  Not asked_x000D_ -5  Missing; Unknown_x000D_ 
# E069_28	Confidence: The ECO	I am going to name a number of organizations. For each one, could you tell me how much confidence you have in them: is it a great deal of confidence, quite a lot of confidence, not very much confidence or none at all?	1  A great deal_x000D_ 2  Quite a lot_x000D_ 3  Not very much_x000D_ 4  None at all_x000D_ -1  Don??t know_x000D_ -2  No answer_x000D_ -4  Not asked_x000D_ -5  Missing; Unknown_x000D_ 
# E069_29	Confidence: The APEC	I am going to name a number of organizations. For each one, could you tell me how much confidence you have in them: is it a great deal of confidence, quite a lot of confidence, not very much confidence or none at all?  The APEC	1  A great deal_x000D_ 2  Quite a lot_x000D_ 3  Not very much_x000D_ 4  None at all_x000D_ -1  Don??t know_x000D_ -2  No answer_x000D_ -4  Not asked_x000D_ -5  Missing; Unknown_x000D_ 
# E069_30	Confidence: The Free Commerce Treaty (Tratado de libre comercio)	I am going to name a number of organizations. For each one, could you tell me how much confidence you have in them: is it a great deal of confidence, quite a lot of confidence, not very much confidence or none at all?  The Free Commerce Treaty (Tratado de libre comercio)	1  A great deal_x000D_ 2  Quite a lot_x000D_ 3  Not very much_x000D_ 4  None at all_x000D_ -1  Don??t know_x000D_ -2  No answer_x000D_ -4  Not asked_x000D_ -5  Missing; Unknown_x000D_ 
# E069_31	Confidence: The United American States Organization (Organizacion de Estados Unidos Americanos - OEA)	I am going to name a number of organizations. For each one, could you tell me how much confidence you have in them: is it a great deal of confidence, quite a lot of confidence, not very much confidence or none at all?	1  A great deal_x000D_ 2  Quite a lot_x000D_ 3  Not very much_x000D_ 4  None at all_x000D_ -1  Don??t know_x000D_ -2  No answer_x000D_ -4  Not asked_x000D_ -5  Missing; Unknown_x000D_ 
# E069_32	Confidence: The "Movimiento en pro de Vieques"(Puerto Rico)	I am going to name a number of organizations. For each one, could you tell me how much confidence you have in them: is it a great deal of confidence, quite a lot of confidence, not very much confidence or none at all?	1  A great deal_x000D_ 2  Quite a lot_x000D_ 3  Not very much_x000D_ 4  None at all_x000D_ -1  Don??t know_x000D_ -2  No answer_x000D_ -4  Not asked_x000D_ -5  Missing; Unknown_x000D_ 
# E069_33	Confidence: Local/Regional Government	I am going to name a number of organizations. For each one, could you tell me how much confidence you have in them: is it a great deal of confidence, quite a lot of confidence, not very much confidence or none at all?	1  A great deal_x000D_ 2  Quite a lot_x000D_ 3  Not very much_x000D_ 4  None at all_x000D_ -1  Don??t know_x000D_ -2  No answer_x000D_ -4  Not asked_x000D_ -5  Missing; Unknown_x000D_ 
# E069_34	Confidence: SADC/SADEC	I am going to name a number of organizations. For each one, could you tell me how much confidence you have in them: is it a great deal of confidence, quite a lot of confidence, not very much confidence or none at all?	1  A great deal_x000D_ 2  Quite a lot_x000D_ 3  Not very much_x000D_ 4  None at all_x000D_ -1  Don??t know_x000D_ -2  No answer_x000D_ -4  Not asked_x000D_ -5  Missing; Unknown_x000D_ 
# E069_35	Confidence: East African Cooperation (EAC)	I am going to name a number of organizations. For each one, could you tell me how much confidence you have in them: is it a great deal of confidence, quite a lot of confidence, not very much confidence or none at all?	1  A great deal_x000D_ 2  Quite a lot_x000D_ 3  Not very much_x000D_ 4  None at all_x000D_ -1  Don??t know_x000D_ -2  No answer_x000D_ -4  Not asked_x000D_ -5  Missing; Unknown_x000D_ 
# E069_38	Confidence: The Presidency	I am going to name a number of organizations. For each one, could you tell me how much confidence you have in them: is it a great deal of confidence, quite a lot of confidence, not very much confidence or none at all?	1  A great deal_x000D_ 2  Quite a lot_x000D_ 3  Not very much_x000D_ 4  None at all_x000D_ -1  Don??t know_x000D_ -2  No answer_x000D_ -4  Not asked_x000D_ -5  Missing; Unknown_x000D_ 
# E069_39	Confidence: The Civil Society Groups	I am going to name a number of organizations. For each one, could you tell me how much confidence you have in them: is it a great deal of confidence, quite a lot of confidence, not very much confidence or none at all?	1  A great deal_x000D_ 2  Quite a lot_x000D_ 3  Not very much_x000D_ 4  None at all_x000D_ -1  Don??t know_x000D_ -2  No answer_x000D_ -4  Not asked_x000D_ -5  Missing; Unknown_x000D_ 
# E069_40	Confidence: Charitable or humanitarian organizations	I am going to name a number of organizations. For each one, could you tell me how much confidence you have in them: is it a great deal of confidence, quite a lot of confidence, not very much confidence or none at all?  Charitable or humanitarian organizations	1  A great deal_x000D_ 2  Quite a lot_x000D_ 3  Not very much_x000D_ 4  None at all_x000D_ -1  Don??t know_x000D_ -2  No answer_x000D_ -4  Not asked_x000D_ -5  Missing; Unknown_x000D_ 
# E069_41	Confidence: Banks	I am going to name a number of organizations. For each one, could you tell me how much confidence you have in them: is it a great deal of confidence, quite a lot of confidence, not very much confidence or none at all?  Banks	1  A great deal_x000D_ 2  Quite a lot_x000D_ 3  Not very much_x000D_ 4  None at all_x000D_ -1  Don??t know_x000D_ -2  No answer_x000D_ -4  Not asked_x000D_ -5  Missing; Unknown_x000D_ 
# E069_42	Confidence: CARICOM	I am going to name a number of organizations. For each one, could you tell me how much confidence you have in them: is it a great deal of confidence, quite a lot of confidence, not very much confidence or none at all?	1  A great deal_x000D_ 2  Quite a lot_x000D_ 3  Not very much_x000D_ 4  None at all_x000D_ -1  Don??t know_x000D_ -2  No answer_x000D_ -4  Not asked_x000D_ -5  Missing; Unknown_x000D_ 
# E069_43	Confidence: CIS	I am going to name a number of organizations. For each one, could you tell me how much confidence you have in them: is it a great deal of confidence, quite a lot of confidence, not very much confidence or none at all?  CIS	1  A great deal_x000D_ 2  Quite a lot_x000D_ 3  Not very much_x000D_ 4  None at all_x000D_ -1  Don??t know_x000D_ -2  No answer_x000D_ -4  Not asked_x000D_ -5  Missing; Unknown_x000D_ 
# E069_44	Confidence: Confidence in CER with Australia	I am going to name a number of organizations. For each one, could you tell me how much confidence you have in them: is it a great deal of confidence, quite a lot of confidence, not very much confidence or none at all?	1  A great deal_x000D_ 2  Quite a lot_x000D_ 3  Not very much_x000D_ 4  None at all_x000D_ -1  Don??t know_x000D_ -2  No answer_x000D_ -4  Not asked_x000D_ -5  Missing; Unknown_x000D_ 
# E069_45	Confidence: International Monetary Found (IMF)	I am going to name a number of organizations. For each one, could you tell me how much confidence you have in them: is it a great deal of confidence, quite a lot of confidence, not very much confidence or none at all?  The International Monetary Fund (IMF)	1  A great deal_x000D_ 2  Quite a lot_x000D_ 3  Not very much_x000D_ 4  None at all_x000D_ -1  Don??t know_x000D_ -2  No answer_x000D_ -4  Not asked_x000D_ -5  Missing; Unknown_x000D_ 
# E069_46	Confidence: Non governmental Organizations (NGOs)	I am going to name a number of organizations. For each one, could you tell me how much confidence you have in them: is it a great deal of confidence, quite a lot of confidence, not very much confidence or none at all?	1  A great deal_x000D_ 2  Quite a lot_x000D_ 3  Not very much_x000D_ 4  None at all_x000D_ -1  Don??t know_x000D_ -2  No answer_x000D_ -4  Not asked_x000D_ -5  Missing; Unknown_x000D_ 
# E069_47	Confidence: The American Forces	I am going to name a number of organizations. For each one, could you tell me how much confidence you have in them: is it a great deal of confidence, quite a lot of confidence, not very much confidence or none at all?	1  A great deal_x000D_ 2  Quite a lot_x000D_ 3  Not very much_x000D_ 4  None at all_x000D_ -1  Don??t know_x000D_ -2  No answer_x000D_ -4  Not asked_x000D_ -5  Missing; Unknown_x000D_ 
# E069_48	Confidence: The non-Iraqi television	I am going to name a number of organizations. For each one, could you tell me how much confidence you have in them: is it a great deal of confidence, quite a lot of confidence, not very much confidence or none at all?	1  A great deal_x000D_ 2  Quite a lot_x000D_ 3  Not very much_x000D_ 4  None at all_x000D_ -1  Don??t know_x000D_ -2  No answer_x000D_ -4  Not asked_x000D_ -5  Missing; Unknown_x000D_ 
# E069_49	Confidence: TV News	I am going to name a number of organizations. For each one, could you tell me how much confidence you have in them: is it a great deal of confidence, quite a lot of confidence, not very much confidence or none at all?	1  A great deal_x000D_ 2  Quite a lot_x000D_ 3  Not very much_x000D_ 4  None at all_x000D_ -1  Don??t know_x000D_ -2  No answer_x000D_ -4  Not asked_x000D_ -5  Missing; Unknown_x000D_ 
# E069_51	Confidence: Religious leaders	I am going to name a number of organizations. For each one, could you tell me how much confidence you have in them: is it a great deal of confidence, quite a lot of confidence, not very much confidence or none at all?	1  A great deal_x000D_ 2  Quite a lot_x000D_ 3  Not very much_x000D_ 4  None at all_x000D_ -1  Don??t know_x000D_ -2  No answer_x000D_ -4  Not asked_x000D_ -5  Missing; Unknown_x000D_ 
# E069_52	Confidence: Evangelic Church	I am going to name a number of organizations. For each one, could you tell me how much confidence you have in them: is it a great deal of confidence, quite a lot of confidence, not very much confidence or none at all?	1  A great deal_x000D_ 2  Quite a lot_x000D_ 3  Not very much_x000D_ 4  None at all_x000D_ -1  Don??t know_x000D_ -2  No answer_x000D_ -4  Not asked_x000D_ -5  Missing; Unknown_x000D_ 
# E069_54	Confidence: Universities	I am going to name a number of organizations. For each one, could you tell me how much confidence you have in them: is it a great deal of confidence, quite a lot of confidence, not very much confidence or none at all?  Universities	1  A great deal_x000D_ 2  Quite a lot_x000D_ 3  Not very much_x000D_ 4  None at all_x000D_ -1  Don??t know_x000D_ -2  No answer_x000D_ -4  Not asked_x000D_ -5  Missing; Unknown_x000D_ 
# E069_55	Confidence: The Organization of the Islamic World	I am going to name a number of organizations. For each one, could you tell me how much confidence you have in them: is it a great deal of confidence, quite a lot of confidence, not very much confidence or none at all?  The Organization of the Islamic Cooperation	1  A great deal_x000D_ 2  Quite a lot_x000D_ 3  Not very much_x000D_ 4  None at all_x000D_ -1  Don??t know_x000D_ -2  No answer_x000D_ -4  Not asked_x000D_ -5  Missing; Unknown_x000D_ 
# E069_56	Confidence: The Organization of American States (OAE)	I am going to name a number of organizations. For each one, could you tell me how much confidence you have in them: is it a great deal of confidence, quite a lot of confidence, not very much confidence or none at all?  The Organization of American States (OAE)	1  A great deal_x000D_ 2  Quite a lot_x000D_ 3  Not very much_x000D_ 4  None at all_x000D_ -1  Don??t know_x000D_ -2  No answer_x000D_ -4  Not asked_x000D_ -5  Missing; Unknown_x000D_ 
# E069_57	Confidence: UNASUR	I am going to name a number of organizations. For each one, could you tell me how much confidence you have in them: is it a great deal of confidence, quite a lot of confidence, not very much confidence or none at all?	1  A great deal_x000D_ 2  Quite a lot_x000D_ 3  Not very much_x000D_ 4  None at all_x000D_ -1  Don??t know_x000D_ -2  No answer_x000D_ -4  Not asked_x000D_ -5  Missing; Unknown_x000D_ 
# E069_58	Confidence: The Arab Maghreb Union	I am going to name a number of organizations. For each one, could you tell me how much confidence you have in them: is it a great deal of confidence, quite a lot of confidence, not very much confidence or none at all?	1  A great deal_x000D_ 2  Quite a lot_x000D_ 3  Not very much_x000D_ 4  None at all_x000D_ -1  Don??t know_x000D_ -2  No answer_x000D_ -4  Not asked_x000D_ -5  Missing; Unknown_x000D_ 
# E069_59	Confidence: Cooperation Council for the Arab states of Gulf (GCC)	I am going to name a number of organizations. For each one, could you tell me how much confidence you have in them: is it a great deal of confidence, quite a lot of confidence, not very much confidence or none at all?  Cooperation Council for the Arab states of Gulf (GCC)	1  A great deal_x000D_ 2  Quite a lot_x000D_ 3  Not very much_x000D_ 4  None at all_x000D_ -1  Don??t know_x000D_ -2  No answer_x000D_ -4  Not asked_x000D_ -5  Missing; Unknown_x000D_ 
# E069_60	Confidence: Mainland government	I am going to name a number of organizations. For each one, could you tell me how much confidence you have in them: is it a great deal of confidence, quite a lot of confidence, not very much confidence or none at all?	1  A great deal_x000D_ 2  Quite a lot_x000D_ 3  Not very much_x000D_ 4  None at all_x000D_ -1  Don??t know_x000D_ -2  No answer_x000D_ -4  Not asked_x000D_ -5  Missing; Unknown_x000D_ 
# E069_61	Confidence: The World Trade Organization (WTO)	I am going to name a number of organizations. For each one, could you tell me how much confidence you have in them: is it a great deal of confidence, quite a lot of confidence, not very much confidence or none at all?  The World Trade Organization (WTO)	1  A great deal_x000D_ 2  Quite a lot_x000D_ 3  Not very much_x000D_ 4  None at all_x000D_ -1  Don??t know_x000D_ -2  No answer_x000D_ -4  Not asked_x000D_ -5  Missing; Unknown_x000D_ 
# E069_62	Confidence: The World Health Organization (WHO)	I am going to name a number of organizations. For each one, could you tell me how much confidence you have in them: is it a great deal of confidence, quite a lot of confidence, not very much confidence or none at all?  The World Health Organization (WHO)	1  A great deal_x000D_ 2  Quite a lot_x000D_ 3  Not very much_x000D_ 4  None at all_x000D_ -1  Don??t know_x000D_ -2  No answer_x000D_ -4  Not asked_x000D_ -5  Missing; Unknown_x000D_ 
# E069_63	Confidence: The World Bank	I am going to name a number of organizations. For each one, could you tell me how much confidence you have in them: is it a great deal of confidence, quite a lot of confidence, not very much confidence or none at all?  The World Bank	1  A great deal_x000D_ 2  Quite a lot_x000D_ 3  Not very much_x000D_ 4  None at all_x000D_ -1  Don??t know_x000D_ -2  No answer_x000D_ -4  Not asked_x000D_ -5  Missing; Unknown_x000D_ 
# E069_64	Confidence: Elections	I am going to name a number of organizations. For each one, could you tell me how much confidence you have in them: is it a great deal of confidence, quite a lot of confidence, not very much confidence or none at all?  Elections	1  A great deal_x000D_ 2  Quite a lot_x000D_ 3  Not very much_x000D_ 4  None at all_x000D_ -1  Don??t know_x000D_ -2  No answer_x000D_ -4  Not asked_x000D_ -5  Missing; Unknown_x000D_ 
# E069_65	Confidence: International Criminal Court (ICC)	I am going to name a number of organizations. For each one, could you tell me how much confidence you have in them: is it a great deal of confidence, quite a lot of confidence, not very much confidence or none at all?  International Criminal Court (ICC)	1  A great deal_x000D_ 2  Quite a lot_x000D_ 3  Not very much_x000D_ 4  None at all_x000D_ -1  Don??t know_x000D_ -2  No answer_x000D_ -4  Not asked_x000D_ -5  Missing; Unknown_x000D_ 
# E069_66	Confidence: UNDP United Nations Development Programme	I am going to name a number of organizations. For each one, could you tell me how much confidence you have in them: is it a great deal of confidence, quite a lot of confidence, not very much confidence or none at all?  UNDP United Nations Development Programme	1  A great deal_x000D_ 2  Quite a lot_x000D_ 3  Not very much_x000D_ 4  None at all_x000D_ -1  Don??t know_x000D_ -2  No answer_x000D_ -4  Not asked_x000D_ -5  Missing; Unknown_x000D_ 
# E196	Extent of political corruption	How widespread do you think bride taking and corruption is in this country?	1  Almost no public officials engaged in it_x000D_ 2  A few are_x000D_ 3  Most are_x000D_ 4  Almost all public officials are engaged in it_x000D_ -1  Don??t know_x000D_ -2  No answer_x000D_ -4  Not asked_x000D_ 
# E263	Vote in elections: local level	Vote in elections: Local level	1  Always_x000D_ 2  Usually_x000D_ 3  Never_x000D_ 4  Not allowed to vote_x000D_ -1  Don??t know_x000D_ -2  No answer_x000D_ -3  Not applicable_x000D_ -4  Not asked_x000D_ -5  Missing; Unknown_x000D_ 
# E264	Vote in elections: National level	Vote in elections: National level	1  Always_x000D_ 2  Usually_x000D_ 3  Never_x000D_ 4  Not allowed to vote_x000D_ -5  Missing; Unknown_x000D_ -4  Not asked in survey_x000D_ -3  Not applicable_x000D_ -2  No answer_x000D_ -1  Don??t know_x000D_ 
# E265_01	How often in country's elections: Votes are counted fairly	In your view, how often do the following things occur in this country's elections?  Votes are counted fairly	1  Very often_x000D_ 2  Fairly often_x000D_ 3  Not often_x000D_ 4  Not at all often_x000D_ -1  Don??t know_x000D_ -2  No answer_x000D_ -3  Not applicable_x000D_ -4  Not asked_x000D_ -5  Missing;Unknown_x000D_ 
# E265_02	How often in country's elections: Opposition candidates are prevented from running	In your view, how often do the following things occur in this country's elections?  Opposition candidates are prevented from running	1  Very often_x000D_ 2  Fairly often_x000D_ 3  Not often_x000D_ 4  Not at all often_x000D_ -1  Don??t know_x000D_ -2  No answer_x000D_ -3  Not applicable_x000D_ -4  Not asked_x000D_ -5  Missing;Unknown_x000D_ 
# E265_03	How often in country's elections: TV news favors the governing party	In your view, how often do the following things occur in this country's elections?  TV news favors the governing party	1  Very often_x000D_ 2  Fairly often_x000D_ 3  Not often_x000D_ 4  Not at all often_x000D_ -1  Don??t know_x000D_ -2  No answer_x000D_ -3  Not applicable_x000D_ -4  Not asked_x000D_ -5  Missing;Unknown_x000D_ 
# E265_04	How often in country's elections: Voters are bribed	In your view, how often do the following things occur in this country's elections?  Voters are bribed	1  Very often_x000D_ 2  Fairly often_x000D_ 3  Not often_x000D_ 4  Not at all often_x000D_ -1  Don??t know_x000D_ -2  No answer_x000D_ -3  Not applicable_x000D_ -4  Not asked_x000D_ -5  Missing;Unknown_x000D_ 
# E265_05	How often in country's elections: Journalists provide fair coverage of elections	In your view, how often do the following things occur in this country's elections?  Journalists provide fair coverage of elections	1  Very often_x000D_ 2  Fairly often_x000D_ 3  Not often_x000D_ 4  Not at all often_x000D_ -1  Don??t know_x000D_ -2  No answer_x000D_ -3  Not applicable_x000D_ -4  Not asked_x000D_ -5  Missing;Unknown_x000D_ 
# E265_06	How often in country's elections: Election officials are fair	In your view, how often do the following things occur in this country's elections?  Election officials are fair	1  Very often_x000D_ 2  Fairly often_x000D_ 3  Not often_x000D_ 4  Not at all often_x000D_ -1  Don??t know_x000D_ -2  No answer_x000D_ -3  Not applicable_x000D_ -4  Not asked_x000D_ -5  Missing;Unknown_x000D_ 
# E265_07	How often in country's elections: Rich people buy elections	In your view, how often do the following things occur in this country's elections?  Rich people buy elections	1  Very often_x000D_ 2  Fairly often_x000D_ 3  Not often_x000D_ 4  Not at all often_x000D_ -1  Don??t know_x000D_ -2  No answer_x000D_ -3  Not applicable_x000D_ -4  Not asked_x000D_ -5  Missing;Unknown_x000D_ 
# E265_08	How often in country's elections: Voters are threatened with  violence at the polls	In your view, how often do the following things occur in this country's elections?  Voters are threatened with  violence at the polls	1  Very often_x000D_ 2  Fairly often_x000D_ 3  Not often_x000D_ 4  Not at all often_x000D_ -1  Don??t know_x000D_ -2  No answer_x000D_ -3  Not applicable_x000D_ -4  Not asked_x000D_ -5  Missing;Unknown_x000D_ 
# E265_09	How often in country's elections: Voters are offered a genuine choice in the elections	In your view, how often do the following things occur in this country's elections?  Voters are offered a genuine choice in the elections	1  Very often_x000D_ 2  Fairly often_x000D_ 3  Not often_x000D_ 4  Not at all often_x000D_ -1  Don??t know_x000D_ -2  No answer_x000D_ -3  Not applicable_x000D_ -4  Not asked_x000D_ -5  Missing;Unknown_x000D_ 
# E265_10	How often in country??s elections: Women have equal opportunities to run the office	In your view, how often do the following things occur in this country's elections?:  Women have equal opportunities to run the office	1  Very often_x000D_ 2  Fairly often_x000D_ 3  Not often_x000D_ 4  Not at all often_x000D_ -1  Don??t know_x000D_ -2  No answer_x000D_ -4  Not asked_x000D_ -5  Missing; Not available_x000D_ 
# X001	Sex	Sex	1  Male_x000D_ 2  Female_x000D_ -1  Don??t know_x000D_ -2  No answer_x000D_ -4  Not asked_x000D_ -5  Missing; Unknown_x000D_ 
# X002	Year of birth	Can you tell me your year of birth, please?	-5  Missing; Unknown -4  Not asked in survey -3  Not applicable -2  No answer -1  Don't know 
# X003	Age		-5  Missing; Unknown -4  Not asked in survey -3  Not applicable -2  No answer -1  Don't know 
# X023R	What age did you complete your education (recoded in intervals)	At what age do you expect you will have completed your education?	1  Less than 12 years_x000D_ 2  13 years_x000D_ 3  14 years_x000D_ 4  15 years_x000D_ 5  16 years_x000D_ 6  17 years_x000D_ 7  18 years_x000D_ 8  19 years_x000D_ 9  20 years_x000D_ 10  21 and more years_x000D_ -5  Missing; Unknown_x000D_ -4  Not asked in survey_x000D_ -3  Not applicable_x000D_ -2  No answer_x000D_ -1  Don??t know_x000D_ 
# X025A2	Highest educational level attained - Respondent	What is the highest educational level that you have attained?	0  Early childhood education (ISCED 0) / no education_x000D_ 1  Primary education (ISCED 1)_x000D_ 2  Lower secondary education (ISCED 2)_x000D_ 3  Upper secondary education (ISCED 3)_x000D_ 4  Post-secondary non-tertiary education (ISCED 4)_x000D_ 5  Short-cycle tertiary education (ISCED 5)_x000D_ 6  Bachelor or equivalent (ISCED 6)_x000D_ 7  Master or equivalent (ISCED 7)_x000D_ 8  Doctoral or equivalent (ISCED 8)_x000D_ -1  Don??t know_x000D_ -2  No answer_x000D_ -3  Not applicable_x000D_ -4  Not asked_x000D_ -5  Missing; Not available_x000D_ 
# X025R	Education level (recoded)		1  Lower_x000D_ 2  Middle_x000D_ 3  Upper_x000D_ -5  Missing; Unknown_x000D_ -4  Not asked in survey_x000D_ -3  Not applicable_x000D_ -2  No answer_x000D_ -1  Don??t know_x000D_ 
# X036E	Respondent - Occupational group (WVS)	To which of the following occupational groups do you belong?	0  Never had a job_x000D_ 1  Professional and technical (for example: doctor, teacher, engineer, artist, accountant, nurse)_x000D_ 2  Higher administrative (for example: banker, executive in big business, high government official, union official)_x000D_ 3  Clerical (for example: secretary, clerk, office manager, civil servant, bookkeeper_x000D_ 4  Sales (for example: sales manager, shop owner, shop assistant, insurance agent, buyer)_x000D_ 5  Service (for example: restaurant owner, police officer, waitress, barber, caretaker)_x000D_ 6  Skilled worker (for example: foreman, motor mechanic, printer, seamstress, tool and die maker, electrician)_x000D_ 7  Semi-skilled worker (for example: bricklayer, bus driver, cannery worker, carpenter, sheet metal worker, baker)_x000D_ 8  Unskilled worker (for example: laborer, porter, unskilled factory worker, cleaner)_x000D_ 9  Farm worker (for example: farm laborer, tractor driver)_x000D_ 10  Farm proprietor, farm manager_x000D_ -1  Don??t know_x000D_ -2  No answer_x000D_ -3  Not applicable_x000D_ -4  Not asked_x000D_ -5  Missing; Not available; Not occupied (KOR,USA)_x000D_ 
# X047R	Income level		1  Low_x000D_ 2  Medium_x000D_ 3  High_x000D_ -1  Don??t know_x000D_ -2  No answer_x000D_ -4  Not asked_x000D_ -5  Missing; Unknown_x000D_ 
# X050C	Urban/Rural habitat		1  Urban_x000D_ 2  Peri.Urban_x000D_ 3  Rural_x000D_ -1  Don't know_x000D_ -2  No answer_x000D_ -3  Not applicable_x000D_ -4  Not asked in survey_x000D_ -5  Missing; Unknown_x000D_ 
# X052	Institution of occupation	Are you working for the government or public institution, for private business or industry, or for a private non-profit organization?. If you do not work currently, characterize your major work in the past!. Do you or did you work for?	1  Public institution 2  Private business 3  Private non-profit organization 4  Self-employed -5  Missing; Unknown -4  Not asked in survey -3  Not applicable -2  No answer -1  Don??t know
# Y014A	TRUSTARMY- Welzel scepticism- 1: Inverse trust in army		0  Very high_x000D_ 0.33  High_x000D_ 0.66  Low_x000D_ 1  Very low_x000D_ -99  Missing_x000D_ 
# Y014B	TRUSTPOLICE- Welzel scepticism- 2: Inverse trust in police		0  Very high_x000D_ 0.33  High_x000D_ 0.66  Low_x000D_ 1  Very low_x000D_ -99  Missing_x000D_ 
# Y014C	TRUSTCOURTS- Welzel scepticism- 3: Inverse trust in courts		0  Very high_x000D_ 0.33  High_x000D_ 0.66  Low_x000D_ 1  Very low_x000D_ -99  Missing_x000D_ 



